### ISSUE TITLE
"expected <block end>" error trying to run matrix-eno-bot for the first time

### ISSUE THREAD

**Issue by eTomte** [8go/matrix-eno-bot#15]
I followed the step by step instructions for installing the bot, and also installed all of the dependencies in the requirements.txt file.  However I'm still getting this error when trying to start up the bot for the first time.  I'm guessing this is a configuration issue, or some missing dependency, but I'm not sure how to troubleshoot this further.

I'm running
Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-70-generic x86_64)
Python 3.8.5

2021-03-28 21:12:05,960 | command_dict [DEBUG] Loading command dictionary at ./commands.yaml
2021-03-28 21:12:06,004 | __main__ [DEBUG] Traceback (most recent call last):
  File "/home/hal/matrix-eno-bot/main.py", line 169, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/hal/matrix-eno-bot/main.py", line 79, in main
    callbacks = Callbacks(client, store, config)
  File "/home/hal/matrix-eno-bot/callbacks.py", line 56, in __init__
    self.command_dict = CommandDict(config.command_dict_filepath)
  File "/home/hal/matrix-eno-bot/command_dict.py", line 39, in __init__
    self.load(command_dict_filepath)
  File "/home/hal/matrix-eno-bot/command_dict.py", line 65, in load
    self.command_dict = yaml.safe_load(fobj.read())
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 131, column 5:
        regex:             "^cheat$|^che ... 
        ^
expected <block end>, but found ','
  in "<unicode string>", line 131, column 121:
     ...  .*$|^chuleta .*$|^cheat.sh .*$",
                                         ^

Thanks!

**Comment by QuailQuark** [comment]
I have just got this code working, I like the look of it.
This is my first gh message :)
I came across this issue and noticed that there were about 3 of the bot command code blocks that had extra trailing commas.
The example in your logs there is one and the others are in the adjacent couple.

So I removed those trailing commas and restarted the systemd service and it worked!
I've had to go through a few issues of my own to get it working so I am _chuffed_!
Thanks @8go &co!

**Comment by 8go** [comment]
Hi @eTomte 

Sorry for that. Congratulations to you @eTomte , you found a tiny bug! Excellent, with your help and issue we can fix it. 

Thanks to @QuailQuark ! He found the solution. It is now fixed in https://github.com/8go/matrix-eno-bot/commit/b9469a4decbfe60719f6191430748b9a3f068981. Job well done @QuailQuark ! And that on your *FIRST* gh message, you are off to a very good start!

Please use the new code and it should all work now. Thanks to both of you! :+1:

**Comment by eTomte** [comment]
Wow, I can't believe it was actually a bug!   I'm really a newb when it comes to python stuff.  Anyway, thanks for fixing it.  I'm up and running now. :)

**Comment by 8go** [comment]
Happy ending for all  :smile:
